#!/bin/bash

PORT=$1

if [ -z "$PORT" ]; then
  exit 2
fi

pushd build
make -j2 && flasher --binary firmware/calibration/fk-atlas-calibration.bin --port $PORT
popd

sleep 1

sudo microcom -f -p $PORT -s 115200
