/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Fri Feb 16 16:43:15 2018. */

#include "fk-atlas.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fk_atlas_AtlasCommand_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_atlas_AtlasCommand, sensor, sensor, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_atlas_AtlasCommand, command, sensor, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_atlas_AtlasReply_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_atlas_AtlasReply, sensor, sensor, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_atlas_AtlasReply, reply, sensor, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_atlas_WireAtlasQuery_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_atlas_WireAtlasQuery, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_atlas_WireAtlasQuery, atlasCommand, type, &fk_atlas_AtlasCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t fk_atlas_Error_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_atlas_Error, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_atlas_Error, message, type, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_atlas_WireAtlasReply_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_atlas_WireAtlasReply, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_atlas_WireAtlasReply, error, type, &fk_atlas_Error_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, fk_atlas_WireAtlasReply, atlasReply, error, &fk_atlas_AtlasReply_fields),
    PB_LAST_FIELD
};






/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_atlas_WireAtlasQuery, atlasCommand) < 65536 && pb_membersize(fk_atlas_WireAtlasReply, error) < 65536 && pb_membersize(fk_atlas_WireAtlasReply, atlasReply) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_fk_atlas_AtlasCommand_fk_atlas_AtlasReply_fk_atlas_WireAtlasQuery_fk_atlas_Error_fk_atlas_WireAtlasReply)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_atlas_WireAtlasQuery, atlasCommand) < 256 && pb_membersize(fk_atlas_WireAtlasReply, error) < 256 && pb_membersize(fk_atlas_WireAtlasReply, atlasReply) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_fk_atlas_AtlasCommand_fk_atlas_AtlasReply_fk_atlas_WireAtlasQuery_fk_atlas_Error_fk_atlas_WireAtlasReply)
#endif


/* @@protoc_insertion_point(eof) */
